export const sliderList = [
    {
        id: 1,
        url: "/images/slider/1.jpg",
    },
    {
        id: 2,
        url: "/images/slider/2.jpg",
    },
    {
        id: 3,
        url: "/images/slider/3.jpg",
    },
    {
        id: 4,
        url: "/images/slider/4.jpg",
    },
];

export const categoryList = [
    {
        id: 1,
        name: "Bakery",
        url: "/images/bread.png",
    },
    {
        id: 2,
        name: "Chicken",
        url: "/images/chicken.png",
    },
    {
        id: 3,
        name: "Cleaning",
        url: "/images/clean-set.png",
    },
    {
        id: 4,
        name: "Food",
        url: "/images/food.png",
    },
    {
        id: 5,
        name: "Fruit",
        url: "/images/fruit.png",
    },
    {
        id: 6,
        name: "Milk",
        url: "/images/milk.png",
    },
    {
        id: 7,
        name: "Vegetables",
        url: "/images/vegetable.png",
    },
];

export const productList = [
    {
        id: 1,
        name: "Bleach",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 5,
        sellingPrice: 4,
        itemQuantityType: "piece",
        slug: "bleach",
        url: "/images/bleach.png",
        categories: ["Cleaning"],
        maxQuantity: 3,
    },
    {
        id: 2,
        name: "Bread",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 2,
        sellingPrice: 1,
        itemQuantityType: "piece",
        slug: "bread",
        url: "/images/bread.png",
        categories: ["Food", "Bakery"],
        maxQuantity: 5,
    },
    {
        id: 3,
        name: "Carrot",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 4,
        sellingPrice: 3,
        itemQuantityType: "kg",
        slug: "carrot",
        url: "/images/carrot.png",
        categories: ["Food", "Vegetables"],
        maxQuantity: 6,
    },
    {
        id: 4,
        name: "Cauliflower",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 6,
        sellingPrice: 5,
        itemQuantityType: "piece",
        slug: "cauliflower",
        url: "/images/cauliflower.png",
        categories: ["Vegetables", "Food"],
        maxQuantity: 2,
    },
    {
        id: 5,
        name: "Chicken",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 8,
        sellingPrice: 7,
        itemQuantityType: "kg",
        slug: "chicken",
        url: "/images/chicken.png",
        categories: ["Chicken", "Food"],
        maxQuantity: 10,
    },
    {
        id: 6,
        name: "Clean Set",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 9,
        sellingPrice: 5,
        itemQuantityType: "piece",
        slug: "clean-set",
        url: "/images/clean-set.png",
        categories: ["Cleaning"],
        maxQuantity: 3,
    },
    {
        id: 7,
        name: "Egg",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 2,
        sellingPrice: 1,
        itemQuantityType: "piece",
        slug: "egg",
        url: "/images/egg.png",
        categories: ["Food", "Chicken"],
        maxQuantity: 4,
    },
    {
        id: 8,
        name: "Food",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 5,
        sellingPrice: 4,
        itemQuantityType: "piece",
        slug: "food",
        url: "/images/food.png",
        categories: ["Food"],
        maxQuantity: 3,
    },
    {
        id: 9,
        name: "Juice",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 4,
        sellingPrice: 3,
        itemQuantityType: "piece",
        slug: "juice",
        url: "/images/juice.png",
        categories: ["Food"],
        maxQuantity: 3,
    },
    {
        id: 10,
        name: "Lemon",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 5,
        sellingPrice: 4,
        itemQuantityType: "kg",
        slug: "lemon",
        url: "/images/lemon.png",
        categories: ["Food", "Vegetables"],
        maxQuantity: 5,
    },
    {
        id: 11,
        name: "Milk",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 5,
        sellingPrice: 4,
        itemQuantityType: "piece",
        slug: "milk",
        url: "/images/milk.png",
        categories: ["Milk", "Food"],
        maxQuantity: 10,
    },
    {
        id: 12,
        name: "Mint",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 2,
        sellingPrice: 1,
        itemQuantityType: "piece",
        slug: "mint",
        url: "/images/mint.png",
        categories: ["Food", "Vegetables"],
        maxQuantity: 5,
    },
    {
        id: 13,
        name: "Orange",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 5,
        sellingPrice: 4,
        itemQuantityType: "kg",
        slug: "orange",
        url: "/images/orange.png",
        categories: ["Food", "Fruit"],
        maxQuantity: 5,
    },
    {
        id: 14,
        name: "Pepper",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 6,
        sellingPrice: 5,
        itemQuantityType: "kg",
        slug: "pepper",
        url: "/images/pepper.png",
        categories: ["Food", "Vegetables"],
        maxQuantity: 4,
    },
    {
        id: 15,
        name: "Pineapple",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 8,
        sellingPrice: 7,
        itemQuantityType: "piece",
        slug: "pineapple",
        url: "/images/pineapple.png",
        categories: ["Food", "Fruit"],
        maxQuantity: 3,
    },
    {
        id: 16,
        name: "Sponge",
        description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer aliquet lorem nec mauris dapibus accumsan. Donec finibus, sem eget pulvinar ornare, quam erat fringilla dui, ac pretium magna arcu id mi. Donec ullamcorper, metus a mattis malesuada, tellus justo fringilla velit, vel elementum justo lorem et nulla.",
        mrp: 3,
        sellingPrice: 2,
        itemQuantityType: "piece",
        slug: "sponge",
        url: "/images/sponge.png",
        categories: ["Cleaning"],
        maxQuantity: 15,
    },
];